GPX-567: Actions werden jeden Montag um 07:00 ausgeführt
gepaplexx/ansible-role-dns pull request #3
Opened 2023-01-10 14:34 UTC by sgartner03

GPX-567: Actions werden jeden Montag um 07:00 ausgeführt

2023-01-10 14:37 UTC, Lucostus requested changes

2023-01-10 14:37 UTC, Lucostus commented on .github/workflows/ci.yml
>      - cron: '30 8 * * 3'
Machen zwei Cronjobs wirklich Sinn?

2023-01-12 08:39 UTC, gattma requested changes

2023-01-12 08:39 UTC, gattma commented on .github/workflows/release.yml
> +    - cron: '0 7 * * 1'
Hier wieder entfernen.

2023-01-12 08:39 UTC, gattma commented on .github/workflows/ci.yml
>      - cron: '30 8 * * 3'
Bitte nur einen Cronjob anlegen und Ausführungszeitpunkt an die anderen Actions anpassen (0 0 * * 1).
Bitte auch den Merge Job um if: ${{ github.event_name != 'schedule' }} erweitern.

2023-01-23 07:24 UTC, gattma approved these changes

2023-01-23 09:07 UTC, merged